[theme]
base = "light"
primaryColor = "#8DBF18"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F5"
textColor = "#333333"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
